upstream_package_name: insights-client
downstream_package_name: insights-client
specfile_path: out/insights-client.spec

srpm_build_deps:
  - gawk
  - rpkg

actions:
  post-upstream-clone:
    - mkdir out
    - rpkg srpm --outdir out
  get-current-version:
    - awk '/^Version:/ {print $2;}' out/insights-client.spec
  create-archive:
    - bash -c 'echo out/insights-client-*.tar.*'
  fix-spec-file:
    - echo 'nothing to fix'

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - rhel-10-x86_64
      - rhel-10-aarch64
      - rhel-10-s390x
      - rhel-10-ppc64le
      - centos-stream-10-x86_64
      - centos-stream-10-aarch64
      - centos-stream-10-s390x
      - centos-stream-10-ppc64le

  - job: copr_build
    trigger: commit
    branch: main
    owner: "@yggdrasil"
    project: latest
    targets:
      - rhel-10-x86_64
      - rhel-10-aarch64
      - rhel-10-s390x
      - rhel-10-ppc64le
      - centos-stream-10-x86_64
      - centos-stream-10-aarch64
      - centos-stream-10-s390x
      - centos-stream-10-ppc64le

  - job: tests
    trigger: pull_request
    identifier: "unit/centos-stream"
    targets:
      - centos-stream-10-x86_64
    labels:
      - unit
    tf_extra_params:
      environments:
        - artifacts:
            - type: repository-file
              id: https://copr.fedorainfracloud.org/coprs/g/yggdrasil/latest/repo/centos-stream-$releasever/group_yggdrasil-latest-centos-stream-$releasever.repo

  - job: tests
    trigger: pull_request
    identifier: "unit/rhel"
    targets:
      rhel-10-x86_64:
        distros:
          - RHEL-10-Nightly
    labels:
      - unit
    tf_extra_params:
      environments:
        - artifacts:
            - type: repository-file
              id: https://copr.fedorainfracloud.org/coprs/g/yggdrasil/latest/repo/rhel-$releasever/group_yggdrasil-latest-rhel-$releasever.repo
          settings:
            provisioning:
              tags:
                BusinessUnit: sst_csi_client_tools
    use_internal_tf: true
