upstream_package_name: insights-client
downstream_package_name: insights-client
specfile_path: out/insights-client.spec

srpm_build_deps:
  - gawk
  - rpkg

actions:
  post-upstream-clone:
    - mkdir out
    - rpkg srpm --outdir out
  get-current-version:
    - awk '/^Version:/ {print $2;}' out/insights-client.spec
  create-archive:
    - bash -c 'echo out/insights-client-*.tar.*'
  fix-spec-file:
    - echo 'nothing to fix'

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - centos-stream-10
      - fedora-all

  - job: copr_build
    trigger: commit
    branch: master
    owner: "@yggdrasil"
    project: latest
    targets:
      - centos-stream-10
      - fedora-all

  - job: tests
    trigger: pull_request
    identifier: "unit/centos-stream"
    targets:
      - centos-stream-10
    labels:
      - unit
    tf_extra_params:
      environments:
        - artifacts:
            - type: repository-file
              id: https://copr.fedorainfracloud.org/coprs/g/yggdrasil/latest/repo/centos-stream-$releasever/group_yggdrasil-latest-centos-stream-$releasever.repo

  - job: tests
    trigger: pull_request
    identifier: "unit/fedora"
    targets:
      - fedora-all
    labels:
      - unit
    tf_extra_params:
      environments:
        - artifacts:
            - type: repository-file
              id: https://copr.fedorainfracloud.org/coprs/g/yggdrasil/latest/repo/fedora-$releasever/group_yggdrasil-latest-fedora-$releasever.repo
