#!/bin/bash
WHICH_PYTHON=$(which python > /dev/null 2>&1)
if [ $? == 1 ]; then echo "Python was not detected. Exiting."; exit 1; fi;

# Check if insights-core is already installed
INSIGHTS_CLIENT_INSTALLED=0
WHICH_INSIGHTS_CLIENT=$(which insights-core > /dev/null 2>&1)
if [ $? == 0 ]; then INSIGHTS_CLIENT_INSTALLED=1; fi;

# Setup flags & placeholders
OPTIND=1
DEVMODE=0
USEGIT=0
NOGPG=0
VERBOSE=0
DONTBUILD=0
SHOWHELP=0
SHOWVERSION=0
ARGS=$@
USEINSTALLEDCORE=0
for arg in "$@"; do
  shift
  case "$arg" in
    "--help") set -- "$@" "-h" ;;
    "--version") set -- "$@" "-v" ;;
	"--devmode") set -- "$@" "-d" ;;
	"--usegit") set -- "$@" "-g" ;;
	"--nogpg") set -- "$@" "-G" ;;
	"--verbose") set -- "$@" "-V" ;;
	"--dontbuild") set -- "$@" "-b" ;;
	"--useinstalledcore") set -- "$@" "-u" ;;
    *)        set -- "$@" "$arg"
  esac
done
while getopts "hvdgGVbu" opt; do
	case "$opt" in
	h) SHOWHELP=1 ;;
	v) SHOWVERSION=1 ;;
	d) DEVMODE=1 ;;
	g) USEGIT=1 ;;
	G) NOGPG=1 ;;
	V) VERBOSE=1 ;;
	b) DONTBUILD=1 ;;
	u) USEINSTALLEDCORE=1;;
	esac
done
shift $((OPTIND-1))
[ "$1" = "--" ] && shift


# Define the help function
# -h flag
function show_help {
	if [ $INSIGHTS_CLIENT_INSTALLED == 1 ]; then
		# Run whatever help mode is already installed
		if [ $DEVMODE == 0 ] && [ $DONTBUILD == 0 ]; then
			insights-core --help
			exit 0;
		# otherwise, build it and verify it as usual
		# then run it
		else
			do_the_things
		fi
	else
		# These are default help options that will need to be updated as the actual client help options are updated
		# This gives the illusion that the package is actually installed...
		echo "Usage: insights-client [options]"
		echo ""
		echo "Options:"
		echo -e "-h | --help\t HALP!"
		echo -e "-v | --version\t Get the version."
		echo -e "-V | --verbose\t Verbose output."
		echo -e "-d | --devmode\t Run in development mode, this uses the local core source instead of reaching out to the mothership."
		echo -e "-g | --usegit\t Retrieve the Core from the Git repo https://github.com/RedHatInsights/insights-client instead of Red Hat mothership."
		echo -e "-G | --nogpg\t Run with no GPG verficiation."
		echo -e "-b | --dontbuild\t Don't build a new core."
		echo -e "-u | --useinstalledcore\t Use whatever insights-core package is already installed."
		exit 0;
	fi
}

# Define the version function
# -v flag
function show_version {
	if [ $INSIGHTS_CLIENT_INSTALLED == 1 ]; then
		# Run whatever version output is already installed
		if [ $DEVMODE == 0 ] && [ $DONTBUILD == 0 ]; then
			insights-core --version
			exit 0;
		# otherwise, build it and verify it as usual
		# then run it
		else
			do_the_things
		fi
	else
		echo "Insights Client Version X.X.X"
		exit 0;
	fi
}

# Define the verbose output
# -V  flag
function verbose_output {
	if [ $VERBOSE == 1 ]; then echo $1; fi;
}


# Define the download function for the client egg
# 1) Not bypassed via devmode through -d flag
EGG_URL="https://cert-api.access.redhat.com/r/insights/static/insights-core.egg"
if [ $USEGIT == 1 ]; then
	EGG_URL="https://raw.githubusercontent.com/RedHatInsights/insights-client/master/insights-core.egg"
fi
function download_client_eggo {
	if [ $DEVMODE == 1 ]; then
		verbose_output "Not retrieving new Core, running in development mode"
	elif [ $USEINSTALLEDCORE == 1 ]; then
		verbose_output "Not building or retrieving new Core, using installed Core"
	else
		verbose_output "Obtaining Insights Client"

		#TODO: Probably need to stick this in /tmp somewhere...
		EGG_CURL=$(curl --insecure --write-out %{http_code} --silent --output insights-core.egg $EGG_URL)
		verbose_output "Client retrieval response "$EGG_CURL""
		if [ $EGG_CURL != 200 ]; then verbose_output "Core retrieval failed"; exit 1; fi;
		if [ $EGG_CURL == 200 ]; then verbose_output "Core retrieval success"; fi;
	fi

	# If we are running in development mode, build the new egg from local
	if [ $DEVMODE == 1 ] && [ $DONTBUILD == 0 ]; then
		verbose_output "Running in development mode, building core from local source"
		python setup.py bdist_egg > /dev/null 2>&1
	elif [ $USEINSTALLEDCORE  == 1 ]; then
		verbose_output "Not building new Core, using installed Core"
	else
		verbose_output "Not building new Core, don't build flag set"
	fi
}

# Define the function to verify the egg
EGG_VERIFICATION=0
if [ $USEINSTALLEDCORE == 1 ]; then NOGPG=1; fi;
function verify_eggo {
	if [ $NOGPG == 0 ]; then
		verbose_output "Verifying core"
		GPG_KEY="redhat.gpg"
		EGG_LOCATION="insights-core.egg"
		if [ $DEVMODE == 1 ]; then 
			GPG_KEY="redhat-dev.gpg";
			EGG_LOCATION="dist/*.egg";
		fi;
		gpg --verify $GPG_KEY $EGG_LOCATION > /dev/null 2>&1
		EGG_VERIFICATION=$?
		# Bail if it doesn't check out
		if [ $EGG_VERIFICATION != 0 ]; then
			verbose_output "Egg verification failed";
			exit 1;
		else
			verbose_output "Egg verification passed";
		fi
	else
		verbose_output "Egg verification bypassed"
	fi
}

# Define the function run the egg and/or install the egg
# Depending on flags
# The egg will check out if:
# 1) GPG is verified
# 2) GPG is bypassed
function hatch_eggo {
	if [ $EGG_VERIFICATION == 0 ]; then
		if [ $DEVMODE == 1 ]; then
			verbose_output "Running development egg"
			python dist/*.egg $ARGS
		elif [ $USEINSTALLEDCORE == 1 ]; then
			verbose_output "Running locally installed core"
			insights-core $ARGS
		else
			verbose_output "Running core from Git or Mothership"
			python insights-core.egg $ARGS
		fi
	fi
}

if [ $SHOWHELP == 1 ]; then show_help; fi
if [ $SHOWVERSION == 1 ]; then show_version; fi

# Verbose stuff
function do_the_things {

	# Download the new Client Eggo if:
	download_client_eggo

	# Verify the eggo if not bypassed via -G flag
	verify_eggo

	# Hatch the egg if it checks out
	hatch_eggo

}

# Main execution procedure
verbose_output "Running Insights Client"
do_the_things