# This testing file is used to identify, track, and fix issues. It allows adding
# new issues as they are discovered and helps work through them step by step.
- name: Set the LoginGraceTime with a regex and file mode to 0600
  hosts: localhost
  become: true
  vars:
    insights_signature_exclude: /hosts,/vars/insights_signature
    insights_signature: !!binary |
      TFMwdExTMUNSVWRKVGlCUVIxQWdVMGxIVGtGVVZWSkZMUzB0TFMwS1ZtVnljMmx2YmpvZ1IyNTFV
      RWNnZGpFS0NtbFJTV05DUVVGQ1EwRkJSMEpSU201b2NrOTNRVUZ2U2tWTmRuYzFPRVFyYWpWd1Rs
      SkJiMUF2TUhKVFowUmxWVU5DTDFoWFl6QlBkRW8xTTNabWJIb0tjWGhWWlRaNWRHcHZiVzkwZVhK
      alpHVjBhMmRyTjFseU9ITTJORVZKTnpsNVUxTndWVk40VTBncmIwWTJVMjkyU0RsSWFUQXJORWxK
      WlRWb1dsQjBRZ3BaUW05Q2FIUmpaRXRTWm1jMGVpOHJXRkYxT0ZOU1luVjZaak5FWTFRNWJVUjJk
      WGROTnprNGVHbFRjbTFZYTNGNVdUUmxkakZVYVZnM2RuRTNaREZGQ25GSGFtZGlOVTlDTUVJNE16
      bG5WM2xaYmtkV1NXNWtNV2xKUjB4UEwzSktaV3hqVHlzeWVFa3pVbGxQWnpRd1lVODRPR0pZZFZw
      cE1VeEllbXhJYm5FS2IydEZkWE5YU2l0VVEwbE9abUo2ZVN0QlIzZENWRXhCTWt4WVozSkZibmwz
      ZW5Fd2NteFNhMmhwTjI1c1luTTBkU3RoWlRGclNISnhPVTVLWkZGRFZncG1jRWxSU2k5eFdUSkxT
      MkYyWTJkUVEyWlNLMEZuZDJsalkwUmtlbEpDV2tWalEycHpWVzFDWlZNdlJrdFVSMFpHUlVneWJF
      SkRhRFpLWjNweFNsbHBDakZVU1c1cWF5dHlWamxuWkhkNk5uZGpWek5JZVhCdWVWZHFLMHBKTVda
      NWFUSnhaa0pKUVRoc1JWZHBiSFU1TTBWTVFXRXhhMHhpY1c5U2RWTmlUbThLWW1wM2RFOWpUSFZG
      VlZabllteHhlV2RpUldwRmNGRXJWMkpUZUdGMVptTnZVRzVWWTFGVWMzZFBZMmMwYVhCWlRUSTFN
      bWczZVZkSVRuaDBUa2hEYndwVVV6bE1NME5zVVVGcE9YTnRTMHRzWm1sVFNXc3JOMUJQZDJGT1dH
      SklObVZRTURobVltcFZWVkV6ZWpOQ1ZXa3lhMDFVZUdWQmVqWm9TbTE0UXk4ekNuQm1MMmRhYkVS
      eFprUk1jVXRHU0V4dVJra3lSa28yVGxGeVMwaFVOa2xVY21SelZ6WkxLM0ZIZFRWcmRWTmhlV04y
      YzBoeVMybEtPVmROWjNKSFRWSUtZVEpEZUdaQ1NHSllhbWhwZGtFNWVEbFZSMjE0ZGt0b1J5dG1j
      VVEyYmpCb1ozcElaM2swVWl0b01ESlRTbE40TkZwTldrNUZOVFZuVkhSdWExUnJNZ3BtT0Vsc1dH
      ZFZWbUZvV0VsS01HZ3pVa3QwYndvOVJXODBUd290TFMwdExVVk9SQ0JRUjFBZ1UwbEhUa0ZVVlZK
      RkxTMHRMUzBL
  tasks:
    - ticket: CCT-1065
      file:
        regexp: '(?i)^\s*LoginGraceTime'
        mode: 0600

- name: Test string with quotes and special characters
  hosts: localhost
  become: true
  vars:
    insights_signature_exclude: /hosts,/vars/insights_signature
    insights_signature: !!binary |
      TFMwdExTMUNSVWRKVGlCUVIxQWdVMGxIVGtGVVZWSkZMUzB0TFMwS1ZtVnljMmx2YmpvZ1IyNTFV
      RWNnZGpFS0NtbFJTV05DUVVGQ1EwRkJSMEpSU201b2NsWlJRVUZ2U2tWTmRuYzFPRVFyYWpWd1Rp
      OW1iMUZCU25SWFZXRnFVRzlZTTFCQ1lubDJTMGxPSzFoV2EyNEtlQzlsUTJ0VWNHWlVWa2gwTTFa
      RVFubFVWVUZVUW01eU1sVTRNRVZxTHpSSUwxazJUemxXU25OVFZESmFTVUpxV1ZRNFdpOTVkSHBh
      TjBoSFMyWk9NZ3BzUzJ0TVJsSnpPRlIyVVdoaVFsRXdNbGt3TTNGa1lWWndaVU52ZGk5VGIwVXlh
      bnBoT0ZVMVkyZENNREZvTjJsYU4zWjNkVFZOUW5KcE9WTkhWRGQxQ25Od1VUZEpOQzlZUkRKRFQx
      Qk9WbVJ4WkNzNU5XUmlNSGxMV21kb2QySnphbnBLZURNM1JWbEhRa05XZUZOTmJuUnVTRzF6V0c1
      RVdsbHFlV0pIYmt3S1EwdFBkRkJCTDFoQ1NXOTVOMjF1VTI5aFVUUXdVVXg0WjJoU1RIaHRUMmxR
      WWxoRU1YUktRVGRGUzBaclZpODJPSGxIYW5FMWFHWnhNVVJEVDFjd013cFlOelJFWW14c1MwNU9T
      bEk1YUU4NGJEUk9TRVZDU210M2MwaHFUMHhhUjBwdVRYUjJSMmxRUmtFNE5HbExhV3g2T0RGbWVX
      cGFTbWd6UzJOTFRYVjRDbU41T0hZME9UWmxOaXRqV0ZWeGRGWkVPVWRPU2pacFFWWjBiSE4wTUc1
      VlpFSk1UM0pyVVhJMGVscDNNRnA1ZDJsblMyOWpSR2wyT1RocVptNTFWREVLYkhaNllYVXlZMnRO
      VTNSeFpYaEZaa1ZPU2psMWMyNXRhWGcwUVU1NVUxQlNlWGxvV0ZwdGVrWnZVMDV1YkhGbU5sRlhZ
      VVZ1YTIxaFJtNUtOVk5XS3dwTk1rSmlkSEV6ZHl0TlYyTmtaVWRvYVZkcGMyWXlNbXRwUkZKV01r
      ZFNSSEZ0UjBOTk1qUjBVRVZvVEhwNVNVeHhjbEpsZDJ4MVRVUm1Nbk0yUjA5TkNtMVNNRGxPT1Vs
      TFNYUm5ZMUpqUjBKaVdGTTJkMUp0TUdKa1UyaFNUMDV4TnpSUmMzZHJlRzAzYlcxd1JUaDZLMjVG
      UTNkWk1XNDBSbXRZYWxFM1lsVUtiVEE0VW1NMU1HczFRMWhCUTNkcVdqTlRXRzR3VWxaT1Qyc3JL
      M1pTU0VodlJFNTVkMUJpYUZkQlQzSndiak5CV1dweWFGWlpZbE4wWVU4clJDOTVjQXBvYUZsYWFV
      aHpOREZNWTBGSVNHZzBWRVowVVFvOVVqY3ZOQW90TFMwdExVVk9SQ0JRUjFBZ1UwbEhUa0ZVVlZK
      RkxTMHRMUzBL
  tasks:
    - ticket: CCT-1065
      value: >
        This_string_contains_special_characters,
        single'quote, double"quote, both'"quotes,
        backslashes\\need to be\\\\escaped!\\
        Newlines?\nYep, they stay.
        Tabs\t	too!
        ~End~

- name: Test a play with an empty map
  hosts: localhost
  become: true
  vars:
    insights_signature_exclude: /hosts,/vars/insights_signature
    insights_signature: !!binary |
      TFMwdExTMUNSVWRKVGlCUVIxQWdVMGxIVGtGVVZWSkZMUzB0TFMwS1ZtVnljMmx2YmpvZ1IyNTFV
      RWNnZGpFS0NtbFJTV05DUVVGQ1EwRkJSMEpSU201b2NsWldRVUZ2U2tWTmRuYzFPRVFyYWpWd1Ru
      cDJaMUZCU2xwR1p6VlBRVUZRU1haSU1XdG5jblJIWWtkM2VFb0taelJTWmk4NGVpODNhV1JOTHpJ
      MFREQTRla2RqVWxCMlVFeDBaRFYxYzI4NU5qaElTa3hEVlhoV2NVMTZaRUZEVUVkV2RqWlBWV0pC
      WWxCUFRsUlJjZ3B0WjNKUEwzTjRUblkzVUhKQ1IzWjRMMjAyYUhSVlprd3lVWFJCU1VaeUswOHpO
      Vk5CTVhaNGF5OUpNMlJJTlVGMU9XVXZNbFExWjBGWWVFdHZRWG96Q2tsd01GVkxOakZKV25WcGRu
      Z3JaV1oxVUhSR2JqQmlkQ3ROZDA5VlJXMVFkUzlsVTJWUVIycFZhSHBRTjJKU1JWaE9LMmR1TlRR
      elZHYzFRMEZqZFRRS09WbDBTV1UyVW5kTU5UaEpUR3hHWms5d01FUkJaMHRoYTFSSFNtYzBSWEIy
      YVRCVWVVbHViRTVYYTNoTVEyOWtMM0FyUVdOd01Wb3hUVTVhWlhWaEx3cEZZbVpsTUVwUU5qWTJi
      VU5SUjBWVFVHbHlUV2xTZW5GNU1sQXplVTh3ZG5ScGVteDNlRkp5UWtVNFIwOVZZMVpxYkhKUGMz
      bEdUM1ZqY0ZNM1IwZHRDbnBLUnpoRFRWbGFSM2hSYVc1VVFuUXZSRmRqU1VReGJrZGxhMGxFYkda
      VmNuSmxXV0ZzV2xCRlkwNDVlVkF6TTNWNEszbGtZVWg2VDNGSU9ITnNlbEFLZUUxRmRITnJVa3BM
      Um5WVFFYRkZiRGdyV0hGV1kyTnBaM2RGVm14VmEyWlFiR3RDUkZJNFdIRlJibHB6ZHpsSk1WcFdV
      MHg2T1V0UlFuVkJORTV6VHdwRVVXRlhNVXRTYTFsaWVHb3liRUp2YkZCeFJpOU5NRzVOVEVZeksx
      ZHdVRUpUUkRONVQzZzJLeko0VWpGd1JuSXdTVVpGTmxWMVUwbFhWMHMyVVVwQ0NqWTNhWE12TUNz
      eFZYcEpjMUY0U2tKbVZXTXdiVkprYzNSS1VFdG5WMHQzWjIxR1QyYzVWRXBFSzFkeVV6ZGtNV2M1
      U1RCWE1VSjRPV3hzVFhGbVVYY0tjekF6VW5RMGFsZHdaUzlPWTJ3NVNHZHJkMG95Y1M4MWVXaHpV
      bTk1ZFVOR1ZUaDZlbkJWVXpKaFYyUlRkR2h3WnpWMlZHUnRaeXRXYlZSNlpqVlNPUXBLYTJrek5I
      WlpTa1puZDIxbGNsZFphVlU0TlFvOWVteDFWd290TFMwdExVVk9SQ0JRUjFBZ1UwbEhUa0ZVVlZK
      RkxTMHRMUzBL
  tasks:
    - ticket: CCT-1101
      value: {}

- name: Test a play with an empty value
  hosts: localhost
  become: true
  vars:
    insights_signature_exclude: /hosts,/vars/insights_signature
    insights_signature: !!binary |
      TFMwdExTMUNSVWRKVGlCUVIxQWdVMGxIVGtGVVZWSkZMUzB0TFMwS1ZtVnljMmx2YmpvZ1IyNTFV
      RWNnZGpFS0NtbFJTV05DUVVGQ1EwRkJSMEpSU201b2NsWmhRVUZ2U2tWTmRuYzFPRVFyYWpWd1Rs
      RnRhMUZCU1VGSFlqSmtSWE5NYkVKdlNrRm5Oa3hHUjB0VGRWWUtXRmhrSzBGcFJrYzBiSFJOV1cx
      RU5tc3dTRmxTUjJkUk9WRXpiREp2VUhoelRqRTFjVzl0TkV4SmJsazRZVkZxYjNGR1N6Vm9UV2N2
      WXpGcWQwdDFTZ3BsUkdFNGNYcFBURFZ4VjNFeVlXcGFlak0wU1d4aFRrMUVZM2xLTm00MVltbFhU
      bHBqZWs0eWEwcHNUaTlJWlV4cGJtSjFiSEJSWnpBMVpYSkxjWFJNQ2xWcFRGbDZkR0pGVGxsQ05r
      dFFWSGhJUjB0R1kzRkVka05hVjBaUWExRm1lVmhOZDNNeVFXeGpSbGRzYVhGcFdWWm9MelJRV1Vv
      NU1IaG1RbVpoWkdjS09EUlFiMFF5WmtkemRtNUdTVGgyTkhsWEwxbFRUV1p4VmpoMmVsUm9hV3RM
      VUdWb1kzcFZRazlNUVdKdVVWUmFObkZ4Y1dSU09YTlpNR2xtZHpSc1lRcGpjRWhrWTNnd1VsRkhM
      MDR3ZHpGUGVHbHphRkZKYXpSd1FYUk1NRXhZUkVwdk5IRklUWEptVTJsTmIwUjVNMVJxV1N0NlZX
      OTZPVUpHV1RWalJHZHJDblJtZVdSRFEyNVFRMnRVYjI1SGNFZDJla3BVTms5d1J6bHJkRTFaTjBj
      NFYxZHdOazh4ZGxwMldUUlRaVU5WVFdkNWJtWnlhbEo0VDBGcUsxZ3haV29LUzBsMlVXUXpaa2xM
      ZDJWSFNtWjNOamxsVTJWbWNGUkVlblIyUlhKM01IZEhNekUyUm1nMWNGRXdWSEJZYlhsV1ZVVmtN
      MlVyYTFGaE1tZzBPVWxvYkFwaWNXdGliV1JHYjFoSVIwSTNXWFE1VlVocVZrWmtabGxqV2k5MlpX
      TmFVR2wzV25aa1FYSnpTRTg0V0VweFNqUndUV2xpZEVsaE5GZEVOVnBKVldkMkNtWjFSbHAyZVRK
      NlJqWk5XWEJQY3pSRlpraGphbUo2TlRkWlVFVllUMGxpWkZVemQyeHdibEZxUVhVeVZXOXBVbFJP
      UnpabVdHMUxVbTlyVjFWMVJIZ0tjME52ZW05amVYbHJZMU5xTTJKNU9YWnhjVTVtUzNsVWRURjVR
      WFptYVdscWMzUnFia3hwV1RsM2JGYzRLMmRZWWxwdmNXeEtSRVEzWmsxeldFOHdOZ3BCYnpWV1ZF
      a3lNVWhhZUUxSVdtZHJLMUpyU1FvOWJHVk5RZ290TFMwdExVVk9SQ0JRUjFBZ1UwbEhUa0ZVVlZK
      RkxTMHRMUzBL
  tasks:
    - ticket: CCT-1102
      value:
