#!/usr/bin/python

__requires__ = 'insights_client'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('insights_client', 'console_scripts', 'insights_client')()
    )
