.\" insights-client - Red Hat Insights
.TH "insights-client" "8" "" "Red Hat Insights" ""
.SH "NAME"
insights\-client \- Red Hat Insights Client tool

.SH "SYNOPSIS"
.B insights-client [options]
.SH "DESCRIPTION"
\fBinsights\-client\fP is designed to help customers proactively resolve issues affecting business operations in Red Hat Enterprise Linux and Red Hat Cloud Infrastructure environments. View alerts or learn more at https://cloud.redhat.com/insights/.  Due to the dynamic nature of this application, some options may become available that are not described in the manual.  Please refer to the output of --help for the most up-to-date options, or view https://access.redhat.com/articles/4099591 for more details.


.SH "OPTIONS"
.IP "-h, --help"
Show this help message and exit.
.IP "--register"
Register host to the Red Hat Insights service.
.IP "--unregister"
Unregister host from the Red Hat Insights service.
.IP "--display-name=DISPLAYNAME"
Display name to use for this host. May be used during registration.
.IP "--group=GROUP"
Group to add this host to. Will create the /etc/insights-client/tags.yaml file if it does not exist.
.IP "--retry=RETRIES"
Number of times to retry uploading. 180 seconds between tries.
.IP "--validate"
Validate the contents of the blacklist configuration.
.IP "--quiet"
Only display error messages to stdout.
.IP "--silent"
Display no messages to stdout.
.IP "--enable-schedule"
Enable automatic scheduling.
.IP "--disable-schedule"
Disable automatic scheduling.
.IP "-c CONF, --conf=CONF"
Pass a custom config file.
.IP "--compressor"
Specifies the compression algorithm to use. Choices are gz, bz2, xz, and none. Defaults to gz.
.IP "--offline"
Collect locally only, do not connect to Insights and do not upload.
.IP "--logging-file"
Specify a logfile other than the default.
.IP "--payload=FILE"
Skip collection and upload a specified archive. Requires --content-type.
.IP "--content-type=TYPE"
Content type of the archive specified with --payload.
.IP "--diagnosis=ID"
Retrieve a remediation for this system.
.IP "--compliance"
Scan the system with OpenSCAP and upload the report.
.IP "--check-results"
Retrieve analysis results from the Red Hat Insights service.
.IP "--show-results"
Display analysis results from the Red Hat Insights service.
.IP "--output-dir=DIR"
Do not compress or upload the collection, and write to a specified directory.
.IP "--output-file=FILE"
Do not upload the archive, and write to a specified file.

.SH "DEBUG OPTIONS"
.IP "--version"
Display version.
.IP "--test-connection"
Test connectivity to Red Hat.
.IP "--force-reregister"
Forcefully reregister this host to Red Hat. Will create a new ID for this host and create a new entry. Use only as directed.
.IP "--verbose"
DEBUG output to stdout
.IP "--no-upload"
Do not upload the archive.
.IP "--keep-archive"
Do not delete archive after upload.
.IP "--support"
Create a support logfile for Red Hat Insights.
.IP "--status"
Check this host's registration status with Red Hat Insights.
.IP "--net-debug"
Log network activity to console.

.SH "MOTD"
A message will be displayed on login about \fBinsights\-client\fP if installed but has not yet been used at least once. To change or remove this message, edit the \fB/etc/insights-client/insights-client.motd\fP file.

.SH "SEE ALSO"
.BR insights-client.conf (5)

\&
