.\" insights-client.conf - Red Hat Insights
.TH "insights-client.conf" "5" "" "Red Hat Insights Configuration" ""
.SH "NAME"
insights\-client.conf \- Red Hat Insights client configuration

.SH "DESCRIPTION"
The \fBinsights\-client.conf\fP file contains configuration information for \fBinsights\-client\fP, the client for the Red Hat Insights service. This file is in an INI style format, option=value, default or example values are shown below.

[insights-client]\&
.IP "loglevel=DEBUG"
Change log level, valid options DEBUG, INFO, WARNING, ERROR, CRITICAL.
.IP "auto_config=True"
Automatically attempt to configure connectivity to Red Hat Insights.
.IP "authmethod=BASIC"
Change authentication method, valid options BASIC, CERT. Default BASIC.\&
.IP "username="
Username to use when authmethod is BASIC.
.IP "password="
Password to use when authmethod is BASIC.
.IP "base_url=cert-api.access.redhat.com:443/r/insights"
Base URL for API Interactions.
.IP "proxy=http://user:pass@192.168.100.50:8080"
URL for the proxy.
.IP "auto_update=True"
Automatically update the dynamic configuration.
.IP "obfuscate=False"
Obfuscate IP addresses.
.IP "obfuscate_hostname=False"
Obfuscate hostname. Requires obfuscate=True.
.IP "cmd_timeout=180"
Timeout for commands run during collection, in seconds.
.IP "http_timeout=10"
Timeout for HTTP calls, in seconds.
.IP "remove_file=/etc/insights-client/remove.conf"
File that can be used to prevent files or commands from being collected or to exclude lines containing a specified word.
.br
Each word specified in patterns will exclude the entire line containing the word in all commands and files.
.br
Keywords will be obfuscated to keyword# in all commands and files and require the Obfuscate option to be True.
.br
This file MUST be in the following format, and MUST match exactly what is in the dynamic_config for file or command name.
.br

.br
[remove]
.br
files=/etc/cluster/cluster.conf,/etc/hosts
.br
commands=/bin/dmseg,/bin/hostname
.br
patterns=password,username
.br
keywords=super$ecret,ultra$ecret
.br

.SH "SEE ALSO"
.BR insights-client (8)
\&
